import type { INodeProperties } from 'n8n-workflow';

const severityOptions = [
	{ name: 'Critical', value: 'CRITICAL' },
	{ name: 'High', value: 'HIGH' },
	{ name: 'Informational', value: 'INFO' },
	{ name: 'Low', value: 'LOW' },
	{ name: 'Medium', value: 'MEDIUM' },
	{ name: 'Unknown', value: 'UNKNOWN' },
];

const statusOptions = [
	{ name: 'In Progress', value: 'IN_PROGRESS' },
	{ name: 'New', value: 'NEW' },
	{ name: 'Resolved', value: 'RESOLVED' },
];

const analystVerdictOptions = [
	{ name: 'False Positive: Benign', value: 'FALSE_POSITIVE_BENIGN' },
	{
		name: 'False Positive: Benign but Suspicious',
		value: 'FALSE_POSITIVE_BENIGN_BUT_SUSPICIOUS',
	},
	{ name: 'False Positive: System Error', value: 'FALSE_POSITIVE_SYSTEM_ERROR' },
	{ name: 'False Positive: Undefined', value: 'FALSE_POSITIVE_UNDEFINED' },
	{ name: 'False Positive: User Error', value: 'FALSE_POSITIVE_USER_ERROR' },
	{
		name: 'True Positive: Advanced Persistent Threat',
		value: 'TRUE_POSITIVE_ADVANCED_PERSISTENT_THREAT',
	},
	{ name: 'True Positive: Benign', value: 'TRUE_POSITIVE_BENIGN' },
	{
		name: 'True Positive: Benign but Suspicious',
		value: 'TRUE_POSITIVE_BENIGN_BUT_SUSPICIOUS',
	},
	{ name: 'True Positive: Data Exfiltration', value: 'TRUE_POSITIVE_DATA_EXFILTRATION' },
	{ name: 'True Positive: Denial of Service', value: 'TRUE_POSITIVE_DENIAL_OF_SERVICE' },
	{ name: 'True Positive: Exploitation Tools', value: 'TRUE_POSITIVE_EXPLOITATION_TOOLS' },
	{ name: 'True Positive: Insider Threat', value: 'TRUE_POSITIVE_INSIDER_THREAT' },
	{ name: 'True Positive: Malware', value: 'TRUE_POSITIVE_MALWARE' },
	{ name: 'True Positive: Phishing Attack', value: 'TRUE_POSITIVE_PHISHING_ATTACK' },
	{ name: 'True Positive: Policy Violation', value: 'TRUE_POSITIVE_POLICY_VIOLATION' },
	{ name: 'True Positive: PUA/Adware', value: 'TRUE_POSITIVE_PUA_ADWARE' },
	{ name: 'True Positive: Ransomware', value: 'TRUE_POSITIVE_RANSOMWARE' },
	{ name: 'True Positive: Unauthorized Access', value: 'TRUE_POSITIVE_UNAUTHORIZED_ACCESS' },
];

const alertId: INodeProperties = {
	displayName: 'Alert ID',
	name: 'alertId',
	type: 'string',
	default: '',
	required: true,
	description: 'ID of the alert',
};

export const sentinelOneProperties: INodeProperties[] = [
	{
		displayName: 'Resource',
		name: 'resource',
		type: 'options',
		noDataExpression: true,
		default: 'alert',
		options: [
			{ name: 'Alert Note', value: 'alertNote' },
			{ name: 'SDL Query', value: 'sdlQuery' },
			{ name: 'Alert', value: 'alert' },
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'get',
		displayOptions: { show: { resource: ['alert'] } },
		options: [
			{
				name: 'Get',
				value: 'get',
				description: 'Get an alert by ID',
				action: 'Get an alert',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get alerts in a management scope',
				action: 'Get many alerts',
			},
			{
				name: 'Update',
				value: 'update',
				description: 'Update one alert through its available actions',
				action: 'Update an alert',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'getAll',
		displayOptions: { show: { resource: ['alertNote'] } },
		options: [
			{
				name: 'Create',
				value: 'create',
				description: 'Create a plain-text or Markdown note on an alert',
				action: 'Create an alert note',
			},
			{
				name: 'Get Many',
				value: 'getAll',
				description: 'Get many notes on an alert',
				action: 'Get many alert notes',
			},
		],
	},
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		default: 'execute',
		displayOptions: { show: { resource: ['sdlQuery'] } },
		options: [
			{
				name: 'Execute',
				value: 'execute',
				description: 'Run a bounded SDL PowerQuery and wait for its result',
				action: 'Execute an SDL query',
			},
		],
	},
	{
		displayName: 'Scope Type',
		name: 'scopeType',
		type: 'options',
		noDataExpression: true,
		default: 'ACCOUNT',
		required: true,
		displayOptions: { show: { resource: ['alertNote', 'alert'] } },
		options: [
			{ name: 'Account', value: 'ACCOUNT' },
			{ name: 'Group', value: 'GROUP' },
			{ name: 'Site', value: 'SITE' },
		],
		description: 'Management boundary used to read or update the alert',
	},
	{
		displayName: 'Account Names or IDs',
		name: 'scopeIds',
		type: 'multiOptions',
		default: [],
		required: true,
		typeOptions: { loadOptionsMethod: 'getAccounts' },
		displayOptions: {
			show: { resource: ['alertNote', 'alert'], scopeType: ['ACCOUNT'] },
		},
		description:
			'Choose from the list, or specify one or more account IDs using an expression. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	{
		displayName: 'Group Names or IDs',
		name: 'scopeIds',
		type: 'multiOptions',
		default: [],
		required: true,
		typeOptions: { loadOptionsMethod: 'getGroups' },
		displayOptions: {
			show: { resource: ['alertNote', 'alert'], scopeType: ['GROUP'] },
		},
		description:
			'Choose from the list, or specify one or more group IDs using an expression. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	{
		displayName: 'Site Names or IDs',
		name: 'scopeIds',
		type: 'multiOptions',
		default: [],
		required: true,
		typeOptions: { loadOptionsMethod: 'getSites' },
		displayOptions: {
			show: { resource: ['alertNote', 'alert'], scopeType: ['SITE'] },
		},
		description:
			'Choose from the list, or specify one or more site IDs using an expression. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	{
		...alertId,
		displayOptions: {
			show: {
				resource: ['alert'],
				operation: ['get', 'update'],
			},
		},
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['alert'], operation: ['getAll'] } },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1 },
		displayOptions: {
			show: { resource: ['alert'], operation: ['getAll'], returnAll: [false] },
		},
		description: 'Max number of results to return',
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: { resource: ['alert'], operation: ['getAll'] } },
		options: [
			{
				displayName: 'Analyst Verdict',
				name: 'analystVerdicts',
				type: 'multiOptions',
				default: [],
				options: analystVerdictOptions,
				description: 'Limit alerts to the selected analyst verdicts',
			},
			{
				displayName: 'Created After',
				name: 'createdAfter',
				type: 'dateTime',
				default: '',
				description: 'Return alerts created at or after this time',
			},
			{
				displayName: 'Created Before',
				name: 'createdBefore',
				type: 'dateTime',
				default: '',
				description: 'Return alerts created before this time',
			},
			{
				displayName: 'External ID',
				name: 'externalId',
				type: 'string',
				default: '',
				description: 'Return alerts whose external ID equals this value',
			},
			{
				displayName: 'Severity',
				name: 'severities',
				type: 'multiOptions',
				default: [],
				options: severityOptions,
				description: 'Limit alerts to the selected severities',
			},
			{
				displayName: 'Status',
				name: 'statuses',
				type: 'multiOptions',
				default: [],
				options: statusOptions,
				description: 'Limit alerts to the selected statuses',
			},
			{
				displayName: 'Ticket ID',
				name: 'ticketId',
				type: 'string',
				default: '',
				description: 'Return alerts whose ticket ID equals this value',
			},
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource: ['alert'], operation: ['update'] } },
		options: [
			{
				displayName: 'Analyst Verdict',
				name: 'analystVerdict',
				type: 'options',
				default: 'FALSE_POSITIVE_UNDEFINED',
				options: analystVerdictOptions,
				description: 'Analyst verdict to set',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				default: 'NEW',
				options: statusOptions,
				description: 'Alert status to set',
			},
			{
				displayName: 'Ticket ID',
				name: 'ticketId',
				type: 'string',
				default: '',
				description: 'Non-empty external ticket ID to set; clearing is not supported in v1',
			},
		],
	},
	{
		displayName: 'Advanced Update Payload',
		name: 'advancedUpdatePayload',
		type: 'json',
		default: '{}',
		displayOptions: { show: { resource: ['alert'], operation: ['update'] } },
		description:
			'Optional payload using only status, analystVerdict, or ticketId. Alert selection and action IDs are not accepted here.',
	},
	{
		...alertId,
		displayOptions: { show: { resource: ['alertNote'] } },
	},
	{
		displayName: 'Return All',
		name: 'returnAll',
		type: 'boolean',
		default: false,
		displayOptions: { show: { resource: ['alertNote'], operation: ['getAll'] } },
		description: 'Whether to return all results or only up to a given limit',
	},
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number',
		default: 50,
		typeOptions: { minValue: 1 },
		displayOptions: {
			show: { resource: ['alertNote'], operation: ['getAll'], returnAll: [false] },
		},
		description: 'Max number of results to return',
	},
	{
		displayName: 'Text',
		name: 'text',
		type: 'string',
		typeOptions: { rows: 5 },
		default: '',
		required: true,
		displayOptions: { show: { resource: ['alertNote'], operation: ['create'] } },
		description: 'Note text; Markdown is passed through unchanged when selected below',
	},
	{
		displayName: 'Content Format',
		name: 'contentType',
		type: 'options',
		default: 'PLAIN_TEXT',
		required: true,
		displayOptions: { show: { resource: ['alertNote'], operation: ['create'] } },
		options: [
			{ name: 'Markdown', value: 'MARKDOWN' },
			{ name: 'Plain Text', value: 'PLAIN_TEXT' },
		],
		description: 'Format of the submitted note text',
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string',
		typeOptions: { rows: 8 },
		default: '',
		required: true,
		displayOptions: { show: { resource: ['sdlQuery'], operation: ['execute'] } },
		description: 'SDL PowerQuery text',
	},
	{
		displayName: 'Start Time',
		name: 'startTime',
		type: 'dateTime',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['sdlQuery'], operation: ['execute'] } },
		description: 'Start of the query time range',
	},
	{
		displayName: 'End Time',
		name: 'endTime',
		type: 'dateTime',
		default: '',
		required: true,
		displayOptions: { show: { resource: ['sdlQuery'], operation: ['execute'] } },
		description: 'End of the query time range',
	},
	{
		displayName: 'Query Scope',
		name: 'queryScope',
		type: 'options',
		noDataExpression: true,
		default: 'tenant',
		required: true,
		displayOptions: { show: { resource: ['sdlQuery'], operation: ['execute'] } },
		options: [
			{ name: 'Entire Tenant', value: 'tenant' },
			{ name: 'Selected Accounts', value: 'accounts' },
		],
		description: 'Tenant or account boundary sent to SDL',
	},
	{
		displayName: 'Account Names or IDs',
		name: 'accountIds',
		type: 'multiOptions',
		default: [],
		required: true,
		typeOptions: { loadOptionsMethod: 'getAccounts' },
		displayOptions: {
			show: { resource: ['sdlQuery'], operation: ['execute'], queryScope: ['accounts'] },
		},
		description:
			'Choose from the list, or specify one or more account IDs using an expression. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
	},
	{
		displayName: 'Output Mode',
		name: 'outputMode',
		type: 'options',
		noDataExpression: true,
		default: 'rows',
		required: true,
		displayOptions: { show: { resource: ['sdlQuery'], operation: ['execute'] } },
		options: [
			{ name: 'Rows', value: 'rows' },
			{ name: 'Table', value: 'table' },
		],
		description: 'Whether to emit one item per row or one item containing the original table',
	},
	{
		displayName: 'Options',
		name: 'options',
		type: 'collection',
		placeholder: 'Add Option',
		default: {},
		displayOptions: { show: { resource: ['sdlQuery'], operation: ['execute'] } },
		options: [
			{
				displayName: 'Maximum Response Size (MiB)',
				name: 'maxResponseSizeMiB',
				type: 'number',
				default: 10,
				typeOptions: { minValue: 1, maxValue: 50 },
				description:
					'Maximum size retained in n8n output after SentinelOne returns the JSON response',
			},
			{
				displayName: 'Maximum Rows',
				name: 'maxRows',
				type: 'number',
				default: 5000,
				typeOptions: { minValue: 1, maxValue: 100000 },
				description: 'Maximum number of SDL result rows to emit',
			},
			{
				displayName: 'Poll Interval (Milliseconds)',
				name: 'pollIntervalMs',
				type: 'number',
				default: 1500,
				typeOptions: { minValue: 1000, maxValue: 10000 },
				description: 'Delay between successful SDL status checks',
			},
			{
				displayName: 'Timeout (Seconds)',
				name: 'timeoutSeconds',
				type: 'number',
				default: 100,
				typeOptions: { minValue: 10, maxValue: 300 },
				description: 'Maximum time for the SDL query lifecycle, excluding final cleanup',
			},
		],
	},
];
